### PR TITLE
Add Vendor CI Run

### PR DESCRIPTION
**Pull request by maiadegraaf**
This PR adds a CI run that automatically updates the vendor nightly.

### CODE REVIEW

**Comment by carlopi** [comment]
This looks fine, one thing I am not super convinced is that this will be triggered on arbitrary commits, possibly not aligned with commit that builds nightly extensions.

Maybe the cron job can be removed, and this triggered externally in the same way we trigger building of extensions (via workflow_dispatch).

But then those are done at the same time (    - cron: "17 0 * * *", see https://github.com/duckdb/duckdb-workflow-trigger/blob/main/.github/workflows/Workflow-Trigger.yml#L13), so that's not really relevant.

**Comment by maiadegraaf** [comment]
If I understand correctly, this specifies that only changes to `vendor.py` or anything that gets changed in `src/duckdb` will trigger the workflow, which is what we want, right?  Specifically since `src/duckdb` shouldn't be changed.

I can remove the cron job, but if I understand correctly I would also need to add a nightly run.

**Comment by carlopi** [comment]
It's more that the cron job might not be OK to invoke at all times, say we decide we will release on commit N, going further than that has no real value.

But that would need either logic to be replicated everywhere or be directed externally.

**Comment by carlopi** [comment]
Anyhow, this looks cool, thanks

**Comment by maiadegraaf** [comment]
Thanks for your comments Carlo! Definitely something to keep in mind for in the future.

**Pull request merged**
